In [5]:
from datetime import date, timedelta
import calendar
import pandas as pd
df = pd.read_csv(r'C:/Users/Ashwin/Downloads/processed_data.csv',parse_dates=['Payment Date'],index_col='Payment Date', sep=r'\s*,\s*')
start_date = date(2018,12,1)
num_months = (date.today().year - 2019)*12 + date.today().month 
data = []
for i in range(num_months):
    for client in df['Client Name'].unique():
        days_in_month = calendar.monthrange(start_date.year, start_date.month)[1]
        date_ = start_date + timedelta(days=days_in_month)
        if date_ < date.today():
            df1 = df[str(date_)[:-3]]
        else :
            break
        count = len(df1[(df1['Client Name']==client)&(df1['Payment Status']=='RESOLVED')])
        total =  len(df1[(df1['Client Name']==client)])
        row = [date_, client, count, total]
        data.append(row)
    start_date=date_
        
df2 = pd.DataFrame(data).set_index(0)
print(df2)

F:\PROGRAMS_F\anaconda3\lib\site-packages\ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.

KeyError: 'Payment Status'

In [3]:
from datetime import date, timedelta
import calendar
import pandas as pd
df = pd.read_csv(r'C:/Users/Ashwin/Downloads/processed_data.csv',parse_dates=['Payment Date'],index_col='Payment Date')
start_date = date(2018,12,1)
num_months = (date.today().year - 2019)*12 + date.today().month 
data = []
for i in range(num_months):
    for client in df['Client Name'].unique():
        days_in_month = calendar.monthrange(start_date.year, start_date.month)[1]
        date_ = start_date + timedelta(days=days_in_month)
        if date_ < date.today():
            df1 = df[str(date_)[:-3]]
        else :
            break
        count =  len(df1[(df1['Client Name']==client)])
        row = [date_, client, count]
        data.append(row)
    start_date=date_
        
df2 = pd.DataFrame(data).set_index(0)
print(df2)

                                       1  2
0
2019-01-01                      jpmchase  5
2019-01-01   hdfcbankltdmumbaiheadoffice  3
2019-01-01                      barclays  0
2019-01-01                          hsbc  0
2019-01-01  bankofbarodamumbaiheadoffice  0
...                                  ... ..
2020-06-01   hdfcbankltdmumbaiheadoffice  9
2020-06-01                      barclays  6
2020-06-01                          hsbc  3
2020-06-01  bankofbarodamumbaiheadoffice  6
2020-06-01                           sbi  0

[108 rows x 2 columns]

In [13]:
import pandas as pd
df = pd.read_csv(r'C:/Users/Ashwin/Desktop/processed_data-1.csv', parse_dates = ['Payment Date'], index_col = 'Payment Date')
df.head()

,Client Name,Legal Entity,Paid Amount,Payment Status
Payment Date,,,,
2019-01-07,jpmchase,citibanknanewyork,30028.000,resolved
2019-01-10,jpmchase,citibanknanewyork,40011.000,resolved
2019-01-17,jpmchase,citibanknanewyork,-40049.000,resolved
2019-01-23,jpmchase,citibanknanewyork,-30043.000,resolved
2019-01-28,hdfcbankltdmumbaiheadoffice,citibanknanewyork,489580.312,resolved

In [14]:
from datetime import date, timedelta
import calendar
start_date = date(2018,12,1)
num_months = (date.today().year - 2019)*12 + date.today().month 
data = []
for i in range(num_months):
    for client in df['Client Name'].unique():
        days_in_month = calendar.monthrange(start_date.year, start_date.month)[1]
        date_ = start_date + timedelta(days=days_in_month)
        if date_ < date.today():
            df1 = df[str(date_)[:-3]]
        else:
            break
        count = len(df1[(df1['Client Name']==client)&(df1['Payment Status']=='resolved')])
        total = len(df1[df1['Client Name']==client])
        row = [date_, client, count, total]
        data.append(row)
    start_date = date_
df2 = pd.DataFrame(data,columns = ['Payment Date','Client Name', 'Resolved', 'Total']).set_index('Payment Date')
df2

                               Client Name  Resolved  Total
Payment Date
2019-01-01                        jpmchase         5      5
2019-01-01     hdfcbankltdmumbaiheadoffice         2      3
2019-01-01                        barclays         0      0
2019-01-01                            hsbc         0      0
2019-01-01    bankofbarodamumbaiheadoffice         0      0
...                                    ...       ...    ...
2020-06-01     hdfcbankltdmumbaiheadoffice         7      9
2020-06-01                        barclays         6      6
2020-06-01                            hsbc         3      3
2020-06-01    bankofbarodamumbaiheadoffice         5      6
2020-06-01                             sbi         0      0

[108 rows x 3 columns]

In [8]:
df=df2
df

                               Client Name  Resolved  Total
Payment Date
2019-01-01                        jpmchase         5      5
2019-01-01     hdfcbankltdmumbaiheadoffice         2      3
2019-01-01                        barclays         0      0
2019-01-01                            hsbc         0      0
2019-01-01    bankofbarodamumbaiheadoffice         0      0
...                                    ...       ...    ...
2020-06-01     hdfcbankltdmumbaiheadoffice         7      9
2020-06-01                        barclays         6      6
2020-06-01                            hsbc         3      3
2020-06-01    bankofbarodamumbaiheadoffice         5      6
2020-06-01                             sbi         0      0

[108 rows x 3 columns]

In [15]:
allClients = ['sbi','hdfcbankltdmumbaiheadoffice', 'jpmchase', 'bankofbarodamumbaiheadoffice', 'hsbc','barclays']
total_resolved={}
total_transaction={}
predicted_resolved={}
predicted_total={}
percentage = {}
for clients in allClients :
    total_resolved[clients]=list()
    total_transaction[clients]=list()
for i in df.iterrows():
    total_resolved[df.iloc[i]['Client Name']].append(df.iloc[i]['Resolved'])
    total_transaction[df.iloc[i]['Client Name']].append(df.iloc[i]['Total'])
for client in allClients :
    model1 = ExponentialSmoothing(np.asarray(total_resolved[client]), trend='add', seasonal='add', seasonal_periods=6, damped=True)
    hw_model1 = model1.fit()
    model2 = ExponentialSmoothing(np.asarray(total_resolved[client]), trend='add', seasonal='add', seasonal_periods=6)
    hw_model2 = model2.fit()
    model = hw_model1 if hw_model1.aic < hw_model2.aic else hw_model2
    predicted_resolved[client]=model.forecast(6)
    
    model1 = ExponentialSmoothing(np.asarray(total_transaction[client]), trend='add', seasonal='add', seasonal_periods=6, damped=True)
    hw_model1 = model1.fit()
    model2 = ExponentialSmoothing(np.asarray(total_transaction[client]), trend='add', seasonal='add', seasonal_periods=6)
    hw_model2 = model2.fit()
    model = hw_model1 if hw_model1.aic < hw_model2.aic else hw_model2
    predicted_total[client]=model.forecast(6)
    
    num=0
    deno=0
    for i in range(6):
        num=predicted_resolved[i]
        deno=predicted_total[i]
    if deno > 0:
        percentage[client]=(num*100)/deno
    else :
        percentage[client]=0
print(percentage)

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types